PUT http://localhost:3003/api/blogs/674d70cde8063f9108e7ae98
Content-Type: application/json

{
"title": "Harry Potter and the Half Blooded Prince.", 
"author": "J.R.R. Tolkien",
"url": "www.tolkien.com",
"likes": 12345,
"id": "674d70cde8063f9108e7ae98"
}