PUT http://localhost:3003/api/blogs/674eed1f242984f639c61a2b
Content-Type: application/json

{
"title": "Harry Potter and the Half Blooded Prince.", 
"author": "J.R.R. Tolkien",
"url": "www.tolkien.com",
"likes": 12346,
"id": "674eed1f242984f639c61a2b"
}